CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  company TEXT NOT NULL,
  total INTEGER NOT NULL,
  remaining INTEGER NOT NULL,
  sold INTEGER NOT NULL
);
